line-length = 100
target-version = "py311"

exclude = [
  ".venv",
  "_archive",
  "cache",
  "logs",
  "rom_databases",
  "temp",
]

[lint]
select = ["E", "F"]
ignore = ["E501"]
per-file-ignores = { "dev/tests/*.py" = ["E402"], "src/utils/__init__.py" = ["F401"] }
